package com.auth.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApiReqHistoryExample {
    /**
     * test_apiReqHistory
     */
    protected String orderByClause;

    /**
     * test_apiReqHistory
     */
    protected boolean distinct;

    /**
     * test_apiReqHistory
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public ApiReqHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRequesttimeIsNull() {
            addCriterion("requestTime is null");
            return (Criteria) this;
        }

        public Criteria andRequesttimeIsNotNull() {
            addCriterion("requestTime is not null");
            return (Criteria) this;
        }

        public Criteria andRequesttimeEqualTo(Date value) {
            addCriterion("requestTime =", value, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeNotEqualTo(Date value) {
            addCriterion("requestTime <>", value, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeGreaterThan(Date value) {
            addCriterion("requestTime >", value, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("requestTime >=", value, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeLessThan(Date value) {
            addCriterion("requestTime <", value, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeLessThanOrEqualTo(Date value) {
            addCriterion("requestTime <=", value, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeIn(List<Date> values) {
            addCriterion("requestTime in", values, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeNotIn(List<Date> values) {
            addCriterion("requestTime not in", values, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeBetween(Date value1, Date value2) {
            addCriterion("requestTime between", value1, value2, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttimeNotBetween(Date value1, Date value2) {
            addCriterion("requestTime not between", value1, value2, "requesttime");
            return (Criteria) this;
        }

        public Criteria andRequesttypeIsNull() {
            addCriterion("requestType is null");
            return (Criteria) this;
        }

        public Criteria andRequesttypeIsNotNull() {
            addCriterion("requestType is not null");
            return (Criteria) this;
        }

        public Criteria andRequesttypeEqualTo(String value) {
            addCriterion("requestType =", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotEqualTo(String value) {
            addCriterion("requestType <>", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeGreaterThan(String value) {
            addCriterion("requestType >", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeGreaterThanOrEqualTo(String value) {
            addCriterion("requestType >=", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeLessThan(String value) {
            addCriterion("requestType <", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeLessThanOrEqualTo(String value) {
            addCriterion("requestType <=", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeLike(String value) {
            addCriterion("requestType like", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotLike(String value) {
            addCriterion("requestType not like", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeIn(List<String> values) {
            addCriterion("requestType in", values, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotIn(List<String> values) {
            addCriterion("requestType not in", values, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeBetween(String value1, String value2) {
            addCriterion("requestType between", value1, value2, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotBetween(String value1, String value2) {
            addCriterion("requestType not between", value1, value2, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequestaddressIsNull() {
            addCriterion("requestAddress is null");
            return (Criteria) this;
        }

        public Criteria andRequestaddressIsNotNull() {
            addCriterion("requestAddress is not null");
            return (Criteria) this;
        }

        public Criteria andRequestaddressEqualTo(String value) {
            addCriterion("requestAddress =", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressNotEqualTo(String value) {
            addCriterion("requestAddress <>", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressGreaterThan(String value) {
            addCriterion("requestAddress >", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressGreaterThanOrEqualTo(String value) {
            addCriterion("requestAddress >=", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressLessThan(String value) {
            addCriterion("requestAddress <", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressLessThanOrEqualTo(String value) {
            addCriterion("requestAddress <=", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressLike(String value) {
            addCriterion("requestAddress like", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressNotLike(String value) {
            addCriterion("requestAddress not like", value, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressIn(List<String> values) {
            addCriterion("requestAddress in", values, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressNotIn(List<String> values) {
            addCriterion("requestAddress not in", values, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressBetween(String value1, String value2) {
            addCriterion("requestAddress between", value1, value2, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andRequestaddressNotBetween(String value1, String value2) {
            addCriterion("requestAddress not between", value1, value2, "requestaddress");
            return (Criteria) this;
        }

        public Criteria andHttpcodeIsNull() {
            addCriterion("httpCode is null");
            return (Criteria) this;
        }

        public Criteria andHttpcodeIsNotNull() {
            addCriterion("httpCode is not null");
            return (Criteria) this;
        }

        public Criteria andHttpcodeEqualTo(String value) {
            addCriterion("httpCode =", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotEqualTo(String value) {
            addCriterion("httpCode <>", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeGreaterThan(String value) {
            addCriterion("httpCode >", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeGreaterThanOrEqualTo(String value) {
            addCriterion("httpCode >=", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeLessThan(String value) {
            addCriterion("httpCode <", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeLessThanOrEqualTo(String value) {
            addCriterion("httpCode <=", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeLike(String value) {
            addCriterion("httpCode like", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotLike(String value) {
            addCriterion("httpCode not like", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeIn(List<String> values) {
            addCriterion("httpCode in", values, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotIn(List<String> values) {
            addCriterion("httpCode not in", values, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeBetween(String value1, String value2) {
            addCriterion("httpCode between", value1, value2, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotBetween(String value1, String value2) {
            addCriterion("httpCode not between", value1, value2, "httpcode");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdIsNull() {
            addCriterion("apiInfo_id is null");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdIsNotNull() {
            addCriterion("apiInfo_id is not null");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdEqualTo(Integer value) {
            addCriterion("apiInfo_id =", value, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdNotEqualTo(Integer value) {
            addCriterion("apiInfo_id <>", value, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdGreaterThan(Integer value) {
            addCriterion("apiInfo_id >", value, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("apiInfo_id >=", value, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdLessThan(Integer value) {
            addCriterion("apiInfo_id <", value, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdLessThanOrEqualTo(Integer value) {
            addCriterion("apiInfo_id <=", value, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdIn(List<Integer> values) {
            addCriterion("apiInfo_id in", values, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdNotIn(List<Integer> values) {
            addCriterion("apiInfo_id not in", values, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdBetween(Integer value1, Integer value2) {
            addCriterion("apiInfo_id between", value1, value2, "apiinfoId");
            return (Criteria) this;
        }

        public Criteria andApiinfoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("apiInfo_id not between", value1, value2, "apiinfoId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}