package com.auth.entity;

import java.util.Date;

public class SysUser {
    /**
     *  id
     */
    private Integer id;

    /**
     * 机构ID officeId
     */
    private Integer officeid;

    /**
     * 姓名 name
     */
    private String name;

    /**
     * 登录名 account
     */
    private String account;

    /**
     * 密码(加密) password
     */
    private String password;

    /**
     * 最后登录IP lastLoginIp
     */
    private String lastloginip;

    /**
     * 最后登录时间 lastLoginTime
     */
    private Date lastlogintime;

    /**
     * 登录总次数 loginCount
     */
    private Integer logincount;

    /**
     * 创建时间 createTime
     */
    private Date createtime;

    /**
     * 是否启用 isEnable
     */
    private Integer isenable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.officeId
     *
     * @return the value of sys_user.officeId
     *
     * @mbg.generated
     */
    public Integer getOfficeid() {
        return officeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.officeId
     *
     * @param officeid the value for sys_user.officeId
     *
     * @mbg.generated
     */
    public void setOfficeid(Integer officeid) {
        this.officeid = officeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name
     *
     * @return the value of sys_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name
     *
     * @param name the value for sys_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.account
     *
     * @return the value of sys_user.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.account
     *
     * @param account the value for sys_user.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.lastLoginIp
     *
     * @return the value of sys_user.lastLoginIp
     *
     * @mbg.generated
     */
    public String getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.lastLoginIp
     *
     * @param lastloginip the value for sys_user.lastLoginIp
     *
     * @mbg.generated
     */
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip == null ? null : lastloginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.lastLoginTime
     *
     * @return the value of sys_user.lastLoginTime
     *
     * @mbg.generated
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.lastLoginTime
     *
     * @param lastlogintime the value for sys_user.lastLoginTime
     *
     * @mbg.generated
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.loginCount
     *
     * @return the value of sys_user.loginCount
     *
     * @mbg.generated
     */
    public Integer getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.loginCount
     *
     * @param logincount the value for sys_user.loginCount
     *
     * @mbg.generated
     */
    public void setLogincount(Integer logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.createTime
     *
     * @return the value of sys_user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.createTime
     *
     * @param createtime the value for sys_user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.isEnable
     *
     * @return the value of sys_user.isEnable
     *
     * @mbg.generated
     */
    public Integer getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.isEnable
     *
     * @param isenable the value for sys_user.isEnable
     *
     * @mbg.generated
     */
    public void setIsenable(Integer isenable) {
        this.isenable = isenable;
    }
}