package com.auth.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TestApi {
    /**
     *  id
     */
    private Integer id;

    /**
     * 接口名称 name
     */
    private String name;

    /**
     * http/https http_type
     */
    private String httpType;

    /**
     * 请求方式 request_type
     */
    private String requestType;

    /**
     * 接口地址 apiAddress
     */
    private String apiaddress;

    /**
     * 请求头 request_head
     */
    private String requestHead;

    /**
     * 请求参数格式 requestParameterType
     */
    private String requestparametertype;

    /**
     * 请求参数 requestParameter
     */
    private String requestparameter;

    /**
     * 状态 status
     */
    private Byte status;

    /**
     * mock状态 mockStatus
     */
    private Byte mockstatus;

    /**
     * HMOCK TTP状态 mock_code
     */
    private String mockCode;

    /**
     * 最近更新 updateTime
     */
    private Date updatetime;

    /**
     * 更新人 userUpdate
     */
    private String userupdate;

    /**
     *  description
     */
    private String description;

    /**
     *  ApiGroupLevelFirstId
     */
    private Integer apigrouplevelfirstid;

    /**
     *  ApiGroupLevelSecondId
     */
    private Integer apigrouplevelsecondid;

    /**
     *  projectId
     */
    private Integer projectid;

    /**
     *  response
     */
    private String response;

    /**
     * mock内容 data
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.id
     *
     * @return the value of test_api.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.id
     *
     * @param id the value for test_api.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.name
     *
     * @return the value of test_api.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.name
     *
     * @param name the value for test_api.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.http_type
     *
     * @return the value of test_api.http_type
     *
     * @mbg.generated
     */
    public String getHttpType() {
        return httpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.http_type
     *
     * @param httpType the value for test_api.http_type
     *
     * @mbg.generated
     */
    public void setHttpType(String httpType) {
        this.httpType = httpType == null ? null : httpType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.request_type
     *
     * @return the value of test_api.request_type
     *
     * @mbg.generated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.request_type
     *
     * @param requestType the value for test_api.request_type
     *
     * @mbg.generated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.apiAddress
     *
     * @return the value of test_api.apiAddress
     *
     * @mbg.generated
     */
    public String getApiaddress() {
        return apiaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.apiAddress
     *
     * @param apiaddress the value for test_api.apiAddress
     *
     * @mbg.generated
     */
    public void setApiaddress(String apiaddress) {
        this.apiaddress = apiaddress == null ? null : apiaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.request_head
     *
     * @return the value of test_api.request_head
     *
     * @mbg.generated
     */
    public String getRequestHead() {
        return requestHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.request_head
     *
     * @param requestHead the value for test_api.request_head
     *
     * @mbg.generated
     */
    public void setRequestHead(String requestHead) {
        this.requestHead = requestHead == null ? null : requestHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.requestParameterType
     *
     * @return the value of test_api.requestParameterType
     *
     * @mbg.generated
     */
    public String getRequestparametertype() {
        return requestparametertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.requestParameterType
     *
     * @param requestparametertype the value for test_api.requestParameterType
     *
     * @mbg.generated
     */
    public void setRequestparametertype(String requestparametertype) {
        this.requestparametertype = requestparametertype == null ? null : requestparametertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.requestParameter
     *
     * @return the value of test_api.requestParameter
     *
     * @mbg.generated
     */
    public String getRequestparameter() {
        return requestparameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.requestParameter
     *
     * @param requestparameter the value for test_api.requestParameter
     *
     * @mbg.generated
     */
    public void setRequestparameter(String requestparameter) {
        this.requestparameter = requestparameter == null ? null : requestparameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.status
     *
     * @return the value of test_api.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.status
     *
     * @param status the value for test_api.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.mockStatus
     *
     * @return the value of test_api.mockStatus
     *
     * @mbg.generated
     */
    public Byte getMockstatus() {
        return mockstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.mockStatus
     *
     * @param mockstatus the value for test_api.mockStatus
     *
     * @mbg.generated
     */
    public void setMockstatus(Byte mockstatus) {
        this.mockstatus = mockstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.mock_code
     *
     * @return the value of test_api.mock_code
     *
     * @mbg.generated
     */
    public String getMockCode() {
        return mockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.mock_code
     *
     * @param mockCode the value for test_api.mock_code
     *
     * @mbg.generated
     */
    public void setMockCode(String mockCode) {
        this.mockCode = mockCode == null ? null : mockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.updateTime
     *
     * @return the value of test_api.updateTime
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss" ,timezone = "GMT+8")
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.updateTime
     *
     * @param updatetime the value for test_api.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.userUpdate
     *
     * @return the value of test_api.userUpdate
     *
     * @mbg.generated
     */
    public String getUserupdate() {
        return userupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.userUpdate
     *
     * @param userupdate the value for test_api.userUpdate
     *
     * @mbg.generated
     */
    public void setUserupdate(String userupdate) {
        this.userupdate = userupdate == null ? null : userupdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.description
     *
     * @return the value of test_api.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.description
     *
     * @param description the value for test_api.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.ApiGroupLevelFirstId
     *
     * @return the value of test_api.ApiGroupLevelFirstId
     *
     * @mbg.generated
     */
    public Integer getApigrouplevelfirstid() {
        return apigrouplevelfirstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.ApiGroupLevelFirstId
     *
     * @param apigrouplevelfirstid the value for test_api.ApiGroupLevelFirstId
     *
     * @mbg.generated
     */
    public void setApigrouplevelfirstid(Integer apigrouplevelfirstid) {
        this.apigrouplevelfirstid = apigrouplevelfirstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.ApiGroupLevelSecondId
     *
     * @return the value of test_api.ApiGroupLevelSecondId
     *
     * @mbg.generated
     */
    public Integer getApigrouplevelsecondid() {
        return apigrouplevelsecondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.ApiGroupLevelSecondId
     *
     * @param apigrouplevelsecondid the value for test_api.ApiGroupLevelSecondId
     *
     * @mbg.generated
     */
    public void setApigrouplevelsecondid(Integer apigrouplevelsecondid) {
        this.apigrouplevelsecondid = apigrouplevelsecondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.projectId
     *
     * @return the value of test_api.projectId
     *
     * @mbg.generated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.projectId
     *
     * @param projectid the value for test_api.projectId
     *
     * @mbg.generated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.response
     *
     * @return the value of test_api.response
     *
     * @mbg.generated
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.response
     *
     * @param response the value for test_api.response
     *
     * @mbg.generated
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_api.data
     *
     * @return the value of test_api.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_api.data
     *
     * @param data the value for test_api.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}