package com.auth.dao;

import com.auth.entity.ApiGroupFirst;
import com.auth.entity.ApiGroupFirstExample;

import java.util.List;

public interface ApiGroupFirstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiGroupLevelFirst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiGroupLevelFirst
     *
     * @mbg.generated
     */
    int insert(ApiGroupFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiGroupLevelFirst
     *
     * @mbg.generated
     */
    int insertSelective(ApiGroupFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiGroupLevelFirst
     *
     * @mbg.generated
     */
    List<ApiGroupFirst> selectByExample(ApiGroupFirstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiGroupLevelFirst
     *
     * @mbg.generated
     */
    ApiGroupFirst selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiGroupLevelFirst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiGroupFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiGroupLevelFirst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiGroupFirst record);
}