package com.auth.dao;

import com.auth.entity.ApiOperationhistory;
import com.auth.entity.ApiOperationhistoryExample;

import java.util.List;

public interface ApiOperationhistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apioperationhistory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apioperationhistory
     *
     * @mbg.generated
     */
    int insert(ApiOperationhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apioperationhistory
     *
     * @mbg.generated
     */
    int insertSelective(ApiOperationhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apioperationhistory
     *
     * @mbg.generated
     */
    List<ApiOperationhistory> selectByExample(ApiOperationhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apioperationhistory
     *
     * @mbg.generated
     */
    ApiOperationhistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apioperationhistory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiOperationhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apioperationhistory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiOperationhistory record);
}