package com.auth.dao;

import com.auth.entity.TestProjectdynamic;
import com.auth.entity.TestProjectdynamicExample;

import java.util.List;

public interface TestProjectdynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_projectdynamic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_projectdynamic
     *
     * @mbg.generated
     */
    int insert(TestProjectdynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_projectdynamic
     *
     * @mbg.generated
     */
    int insertSelective(TestProjectdynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_projectdynamic
     *
     * @mbg.generated
     */
    List<TestProjectdynamic> selectByExample(TestProjectdynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_projectdynamic
     *
     * @mbg.generated
     */
    TestProjectdynamic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_projectdynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestProjectdynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_projectdynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestProjectdynamic record);
}