package com.auth.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class ApiReqHistory {
    /**
     *  id
     */
    private Integer id;

    /**
     * 请求时间 requestTime
     */
    private Date requesttime;

    /**
     * 请求类型 requestType
     */
    private String requesttype;

    /**
     * 请求地址 requestAddress
     */
    private String requestaddress;

    /**
     * 状态嘛 httpCode
     */
    private String httpcode;

    /**
     * 对应的接口 apiInfo_id
     */
    private Integer apiinfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_apiReqHistory.id
     *
     * @return the value of test_apiReqHistory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_apiReqHistory.id
     *
     * @param id the value for test_apiReqHistory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_apiReqHistory.requestTime
     *
     * @return the value of test_apiReqHistory.requestTime
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss" ,timezone = "GMT+8")
    public Date getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_apiReqHistory.requestTime
     *
     * @param requesttime the value for test_apiReqHistory.requestTime
     *
     * @mbg.generated
     */
    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_apiReqHistory.requestType
     *
     * @return the value of test_apiReqHistory.requestType
     *
     * @mbg.generated
     */
    public String getRequesttype() {
        return requesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_apiReqHistory.requestType
     *
     * @param requesttype the value for test_apiReqHistory.requestType
     *
     * @mbg.generated
     */
    public void setRequesttype(String requesttype) {
        this.requesttype = requesttype == null ? null : requesttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_apiReqHistory.requestAddress
     *
     * @return the value of test_apiReqHistory.requestAddress
     *
     * @mbg.generated
     */
    public String getRequestaddress() {
        return requestaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_apiReqHistory.requestAddress
     *
     * @param requestaddress the value for test_apiReqHistory.requestAddress
     *
     * @mbg.generated
     */
    public void setRequestaddress(String requestaddress) {
        this.requestaddress = requestaddress == null ? null : requestaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_apiReqHistory.httpCode
     *
     * @return the value of test_apiReqHistory.httpCode
     *
     * @mbg.generated
     */
    public String getHttpcode() {
        return httpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_apiReqHistory.httpCode
     *
     * @param httpcode the value for test_apiReqHistory.httpCode
     *
     * @mbg.generated
     */
    public void setHttpcode(String httpcode) {
        this.httpcode = httpcode == null ? null : httpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_apiReqHistory.apiInfo_id
     *
     * @return the value of test_apiReqHistory.apiInfo_id
     *
     * @mbg.generated
     */
    public Integer getApiinfoId() {
        return apiinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_apiReqHistory.apiInfo_id
     *
     * @param apiinfoId the value for test_apiReqHistory.apiInfo_id
     *
     * @mbg.generated
     */
    public void setApiinfoId(Integer apiinfoId) {
        this.apiinfoId = apiinfoId;
    }
}