package com.auth.entity;

public class CaseApi {
    /**
     *  id
     */
    private Integer id;

    /**
     * 名称 name
     */
    private String name;

    /**
     * http/https http_type
     */
    private String httpType;

    /**
     * 请求类型 requestType
     */
    private String requesttype;

    /**
     * 地址 address
     */
    private String address;

    /**
     * 头部 header
     */
    private String header;

    /**
     * 参数类型 requestParameterType
     */
    private String requestparametertype;

    /**
     * 请求参数 requestParamter
     */
    private String requestparamter;

    /**
     * 校验类型 examineType
     */
    private String examinetype;

    /**
     * httpcode httpCode
     */
    private String httpcode;

    /**
     * 响应数据 responseData
     */
    private String responsedata;

    /**
     * caseid autoCase_id
     */
    private Integer autocaseId;

    /**
     * 接口ID api_id
     */
    private Integer apiId;

    /**
     * 项目ID project_id
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.id
     *
     * @return the value of test_caseApi.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.id
     *
     * @param id the value for test_caseApi.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.name
     *
     * @return the value of test_caseApi.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.name
     *
     * @param name the value for test_caseApi.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.http_type
     *
     * @return the value of test_caseApi.http_type
     *
     * @mbg.generated
     */
    public String getHttpType() {
        return httpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.http_type
     *
     * @param httpType the value for test_caseApi.http_type
     *
     * @mbg.generated
     */
    public void setHttpType(String httpType) {
        this.httpType = httpType == null ? null : httpType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.requestType
     *
     * @return the value of test_caseApi.requestType
     *
     * @mbg.generated
     */
    public String getRequesttype() {
        return requesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.requestType
     *
     * @param requesttype the value for test_caseApi.requestType
     *
     * @mbg.generated
     */
    public void setRequesttype(String requesttype) {
        this.requesttype = requesttype == null ? null : requesttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.address
     *
     * @return the value of test_caseApi.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.address
     *
     * @param address the value for test_caseApi.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.header
     *
     * @return the value of test_caseApi.header
     *
     * @mbg.generated
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.header
     *
     * @param header the value for test_caseApi.header
     *
     * @mbg.generated
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.requestParameterType
     *
     * @return the value of test_caseApi.requestParameterType
     *
     * @mbg.generated
     */
    public String getRequestparametertype() {
        return requestparametertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.requestParameterType
     *
     * @param requestparametertype the value for test_caseApi.requestParameterType
     *
     * @mbg.generated
     */
    public void setRequestparametertype(String requestparametertype) {
        this.requestparametertype = requestparametertype == null ? null : requestparametertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.requestParamter
     *
     * @return the value of test_caseApi.requestParamter
     *
     * @mbg.generated
     */
    public String getRequestparamter() {
        return requestparamter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.requestParamter
     *
     * @param requestparamter the value for test_caseApi.requestParamter
     *
     * @mbg.generated
     */
    public void setRequestparamter(String requestparamter) {
        this.requestparamter = requestparamter == null ? null : requestparamter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.examineType
     *
     * @return the value of test_caseApi.examineType
     *
     * @mbg.generated
     */
    public String getExaminetype() {
        return examinetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.examineType
     *
     * @param examinetype the value for test_caseApi.examineType
     *
     * @mbg.generated
     */
    public void setExaminetype(String examinetype) {
        this.examinetype = examinetype == null ? null : examinetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.httpCode
     *
     * @return the value of test_caseApi.httpCode
     *
     * @mbg.generated
     */
    public String getHttpcode() {
        return httpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.httpCode
     *
     * @param httpcode the value for test_caseApi.httpCode
     *
     * @mbg.generated
     */
    public void setHttpcode(String httpcode) {
        this.httpcode = httpcode == null ? null : httpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.responseData
     *
     * @return the value of test_caseApi.responseData
     *
     * @mbg.generated
     */
    public String getResponsedata() {
        return responsedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.responseData
     *
     * @param responsedata the value for test_caseApi.responseData
     *
     * @mbg.generated
     */
    public void setResponsedata(String responsedata) {
        this.responsedata = responsedata == null ? null : responsedata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.autoCase_id
     *
     * @return the value of test_caseApi.autoCase_id
     *
     * @mbg.generated
     */
    public Integer getAutocaseId() {
        return autocaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.autoCase_id
     *
     * @param autocaseId the value for test_caseApi.autoCase_id
     *
     * @mbg.generated
     */
    public void setAutocaseId(Integer autocaseId) {
        this.autocaseId = autocaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.api_id
     *
     * @return the value of test_caseApi.api_id
     *
     * @mbg.generated
     */
    public Integer getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.api_id
     *
     * @param apiId the value for test_caseApi.api_id
     *
     * @mbg.generated
     */
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_caseApi.project_id
     *
     * @return the value of test_caseApi.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_caseApi.project_id
     *
     * @param projectId the value for test_caseApi.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}