package com.auth.entity;

import java.util.ArrayList;
import java.util.List;

public class CaseApiExample {
    /**
     * test_caseApi
     */
    protected String orderByClause;

    /**
     * test_caseApi
     */
    protected boolean distinct;

    /**
     * test_caseApi
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public CaseApiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andHttpTypeIsNull() {
            addCriterion("http_type is null");
            return (Criteria) this;
        }

        public Criteria andHttpTypeIsNotNull() {
            addCriterion("http_type is not null");
            return (Criteria) this;
        }

        public Criteria andHttpTypeEqualTo(String value) {
            addCriterion("http_type =", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotEqualTo(String value) {
            addCriterion("http_type <>", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeGreaterThan(String value) {
            addCriterion("http_type >", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("http_type >=", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeLessThan(String value) {
            addCriterion("http_type <", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeLessThanOrEqualTo(String value) {
            addCriterion("http_type <=", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeLike(String value) {
            addCriterion("http_type like", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotLike(String value) {
            addCriterion("http_type not like", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeIn(List<String> values) {
            addCriterion("http_type in", values, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotIn(List<String> values) {
            addCriterion("http_type not in", values, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeBetween(String value1, String value2) {
            addCriterion("http_type between", value1, value2, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotBetween(String value1, String value2) {
            addCriterion("http_type not between", value1, value2, "httpType");
            return (Criteria) this;
        }

        public Criteria andRequesttypeIsNull() {
            addCriterion("requestType is null");
            return (Criteria) this;
        }

        public Criteria andRequesttypeIsNotNull() {
            addCriterion("requestType is not null");
            return (Criteria) this;
        }

        public Criteria andRequesttypeEqualTo(String value) {
            addCriterion("requestType =", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotEqualTo(String value) {
            addCriterion("requestType <>", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeGreaterThan(String value) {
            addCriterion("requestType >", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeGreaterThanOrEqualTo(String value) {
            addCriterion("requestType >=", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeLessThan(String value) {
            addCriterion("requestType <", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeLessThanOrEqualTo(String value) {
            addCriterion("requestType <=", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeLike(String value) {
            addCriterion("requestType like", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotLike(String value) {
            addCriterion("requestType not like", value, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeIn(List<String> values) {
            addCriterion("requestType in", values, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotIn(List<String> values) {
            addCriterion("requestType not in", values, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeBetween(String value1, String value2) {
            addCriterion("requestType between", value1, value2, "requesttype");
            return (Criteria) this;
        }

        public Criteria andRequesttypeNotBetween(String value1, String value2) {
            addCriterion("requestType not between", value1, value2, "requesttype");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andHeaderIsNull() {
            addCriterion("`header` is null");
            return (Criteria) this;
        }

        public Criteria andHeaderIsNotNull() {
            addCriterion("`header` is not null");
            return (Criteria) this;
        }

        public Criteria andHeaderEqualTo(String value) {
            addCriterion("`header` =", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotEqualTo(String value) {
            addCriterion("`header` <>", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderGreaterThan(String value) {
            addCriterion("`header` >", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderGreaterThanOrEqualTo(String value) {
            addCriterion("`header` >=", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderLessThan(String value) {
            addCriterion("`header` <", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderLessThanOrEqualTo(String value) {
            addCriterion("`header` <=", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderLike(String value) {
            addCriterion("`header` like", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotLike(String value) {
            addCriterion("`header` not like", value, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderIn(List<String> values) {
            addCriterion("`header` in", values, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotIn(List<String> values) {
            addCriterion("`header` not in", values, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderBetween(String value1, String value2) {
            addCriterion("`header` between", value1, value2, "header");
            return (Criteria) this;
        }

        public Criteria andHeaderNotBetween(String value1, String value2) {
            addCriterion("`header` not between", value1, value2, "header");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeIsNull() {
            addCriterion("requestParameterType is null");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeIsNotNull() {
            addCriterion("requestParameterType is not null");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeEqualTo(String value) {
            addCriterion("requestParameterType =", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotEqualTo(String value) {
            addCriterion("requestParameterType <>", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeGreaterThan(String value) {
            addCriterion("requestParameterType >", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeGreaterThanOrEqualTo(String value) {
            addCriterion("requestParameterType >=", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeLessThan(String value) {
            addCriterion("requestParameterType <", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeLessThanOrEqualTo(String value) {
            addCriterion("requestParameterType <=", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeLike(String value) {
            addCriterion("requestParameterType like", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotLike(String value) {
            addCriterion("requestParameterType not like", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeIn(List<String> values) {
            addCriterion("requestParameterType in", values, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotIn(List<String> values) {
            addCriterion("requestParameterType not in", values, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeBetween(String value1, String value2) {
            addCriterion("requestParameterType between", value1, value2, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotBetween(String value1, String value2) {
            addCriterion("requestParameterType not between", value1, value2, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparamterIsNull() {
            addCriterion("requestParamter is null");
            return (Criteria) this;
        }

        public Criteria andRequestparamterIsNotNull() {
            addCriterion("requestParamter is not null");
            return (Criteria) this;
        }

        public Criteria andRequestparamterEqualTo(String value) {
            addCriterion("requestParamter =", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterNotEqualTo(String value) {
            addCriterion("requestParamter <>", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterGreaterThan(String value) {
            addCriterion("requestParamter >", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterGreaterThanOrEqualTo(String value) {
            addCriterion("requestParamter >=", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterLessThan(String value) {
            addCriterion("requestParamter <", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterLessThanOrEqualTo(String value) {
            addCriterion("requestParamter <=", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterLike(String value) {
            addCriterion("requestParamter like", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterNotLike(String value) {
            addCriterion("requestParamter not like", value, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterIn(List<String> values) {
            addCriterion("requestParamter in", values, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterNotIn(List<String> values) {
            addCriterion("requestParamter not in", values, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterBetween(String value1, String value2) {
            addCriterion("requestParamter between", value1, value2, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andRequestparamterNotBetween(String value1, String value2) {
            addCriterion("requestParamter not between", value1, value2, "requestparamter");
            return (Criteria) this;
        }

        public Criteria andExaminetypeIsNull() {
            addCriterion("examineType is null");
            return (Criteria) this;
        }

        public Criteria andExaminetypeIsNotNull() {
            addCriterion("examineType is not null");
            return (Criteria) this;
        }

        public Criteria andExaminetypeEqualTo(String value) {
            addCriterion("examineType =", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeNotEqualTo(String value) {
            addCriterion("examineType <>", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeGreaterThan(String value) {
            addCriterion("examineType >", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeGreaterThanOrEqualTo(String value) {
            addCriterion("examineType >=", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeLessThan(String value) {
            addCriterion("examineType <", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeLessThanOrEqualTo(String value) {
            addCriterion("examineType <=", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeLike(String value) {
            addCriterion("examineType like", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeNotLike(String value) {
            addCriterion("examineType not like", value, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeIn(List<String> values) {
            addCriterion("examineType in", values, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeNotIn(List<String> values) {
            addCriterion("examineType not in", values, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeBetween(String value1, String value2) {
            addCriterion("examineType between", value1, value2, "examinetype");
            return (Criteria) this;
        }

        public Criteria andExaminetypeNotBetween(String value1, String value2) {
            addCriterion("examineType not between", value1, value2, "examinetype");
            return (Criteria) this;
        }

        public Criteria andHttpcodeIsNull() {
            addCriterion("httpCode is null");
            return (Criteria) this;
        }

        public Criteria andHttpcodeIsNotNull() {
            addCriterion("httpCode is not null");
            return (Criteria) this;
        }

        public Criteria andHttpcodeEqualTo(String value) {
            addCriterion("httpCode =", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotEqualTo(String value) {
            addCriterion("httpCode <>", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeGreaterThan(String value) {
            addCriterion("httpCode >", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeGreaterThanOrEqualTo(String value) {
            addCriterion("httpCode >=", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeLessThan(String value) {
            addCriterion("httpCode <", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeLessThanOrEqualTo(String value) {
            addCriterion("httpCode <=", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeLike(String value) {
            addCriterion("httpCode like", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotLike(String value) {
            addCriterion("httpCode not like", value, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeIn(List<String> values) {
            addCriterion("httpCode in", values, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotIn(List<String> values) {
            addCriterion("httpCode not in", values, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeBetween(String value1, String value2) {
            addCriterion("httpCode between", value1, value2, "httpcode");
            return (Criteria) this;
        }

        public Criteria andHttpcodeNotBetween(String value1, String value2) {
            addCriterion("httpCode not between", value1, value2, "httpcode");
            return (Criteria) this;
        }

        public Criteria andResponsedataIsNull() {
            addCriterion("responseData is null");
            return (Criteria) this;
        }

        public Criteria andResponsedataIsNotNull() {
            addCriterion("responseData is not null");
            return (Criteria) this;
        }

        public Criteria andResponsedataEqualTo(String value) {
            addCriterion("responseData =", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataNotEqualTo(String value) {
            addCriterion("responseData <>", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataGreaterThan(String value) {
            addCriterion("responseData >", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataGreaterThanOrEqualTo(String value) {
            addCriterion("responseData >=", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataLessThan(String value) {
            addCriterion("responseData <", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataLessThanOrEqualTo(String value) {
            addCriterion("responseData <=", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataLike(String value) {
            addCriterion("responseData like", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataNotLike(String value) {
            addCriterion("responseData not like", value, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataIn(List<String> values) {
            addCriterion("responseData in", values, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataNotIn(List<String> values) {
            addCriterion("responseData not in", values, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataBetween(String value1, String value2) {
            addCriterion("responseData between", value1, value2, "responsedata");
            return (Criteria) this;
        }

        public Criteria andResponsedataNotBetween(String value1, String value2) {
            addCriterion("responseData not between", value1, value2, "responsedata");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdIsNull() {
            addCriterion("autoCase_id is null");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdIsNotNull() {
            addCriterion("autoCase_id is not null");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdEqualTo(Integer value) {
            addCriterion("autoCase_id =", value, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdNotEqualTo(Integer value) {
            addCriterion("autoCase_id <>", value, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdGreaterThan(Integer value) {
            addCriterion("autoCase_id >", value, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("autoCase_id >=", value, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdLessThan(Integer value) {
            addCriterion("autoCase_id <", value, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdLessThanOrEqualTo(Integer value) {
            addCriterion("autoCase_id <=", value, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdIn(List<Integer> values) {
            addCriterion("autoCase_id in", values, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdNotIn(List<Integer> values) {
            addCriterion("autoCase_id not in", values, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdBetween(Integer value1, Integer value2) {
            addCriterion("autoCase_id between", value1, value2, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andAutocaseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("autoCase_id not between", value1, value2, "autocaseId");
            return (Criteria) this;
        }

        public Criteria andApiIdIsNull() {
            addCriterion("api_id is null");
            return (Criteria) this;
        }

        public Criteria andApiIdIsNotNull() {
            addCriterion("api_id is not null");
            return (Criteria) this;
        }

        public Criteria andApiIdEqualTo(Integer value) {
            addCriterion("api_id =", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotEqualTo(Integer value) {
            addCriterion("api_id <>", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdGreaterThan(Integer value) {
            addCriterion("api_id >", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("api_id >=", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLessThan(Integer value) {
            addCriterion("api_id <", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLessThanOrEqualTo(Integer value) {
            addCriterion("api_id <=", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdIn(List<Integer> values) {
            addCriterion("api_id in", values, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotIn(List<Integer> values) {
            addCriterion("api_id not in", values, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdBetween(Integer value1, Integer value2) {
            addCriterion("api_id between", value1, value2, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("api_id not between", value1, value2, "apiId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_caseApi
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_caseApi
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}