package com.auth.entity;

public class TestGlobalHost {
    /**
     *  id
     */
    private Integer id;

    /**
     * 名称 name
     */
    private String name;

    /**
     * Host地址 host
     */
    private String host;

    /**
     *  description
     */
    private String description;

    /**
     * 状态 status
     */
    private Byte status;

    /**
     *  project_id
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_globalHost.id
     *
     * @return the value of test_globalHost.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_globalHost.id
     *
     * @param id the value for test_globalHost.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_globalHost.name
     *
     * @return the value of test_globalHost.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_globalHost.name
     *
     * @param name the value for test_globalHost.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_globalHost.host
     *
     * @return the value of test_globalHost.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_globalHost.host
     *
     * @param host the value for test_globalHost.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_globalHost.description
     *
     * @return the value of test_globalHost.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_globalHost.description
     *
     * @param description the value for test_globalHost.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_globalHost.status
     *
     * @return the value of test_globalHost.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_globalHost.status
     *
     * @param status the value for test_globalHost.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_globalHost.project_id
     *
     * @return the value of test_globalHost.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_globalHost.project_id
     *
     * @param projectId the value for test_globalHost.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}