package com.auth.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestApiExample {
    /**
     * test_api
     */
    protected String orderByClause;

    /**
     * test_api
     */
    protected boolean distinct;

    /**
     * test_api
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public TestApiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_api
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andHttpTypeIsNull() {
            addCriterion("http_type is null");
            return (Criteria) this;
        }

        public Criteria andHttpTypeIsNotNull() {
            addCriterion("http_type is not null");
            return (Criteria) this;
        }

        public Criteria andHttpTypeEqualTo(String value) {
            addCriterion("http_type =", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotEqualTo(String value) {
            addCriterion("http_type <>", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeGreaterThan(String value) {
            addCriterion("http_type >", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("http_type >=", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeLessThan(String value) {
            addCriterion("http_type <", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeLessThanOrEqualTo(String value) {
            addCriterion("http_type <=", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeLike(String value) {
            addCriterion("http_type like", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotLike(String value) {
            addCriterion("http_type not like", value, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeIn(List<String> values) {
            addCriterion("http_type in", values, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotIn(List<String> values) {
            addCriterion("http_type not in", values, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeBetween(String value1, String value2) {
            addCriterion("http_type between", value1, value2, "httpType");
            return (Criteria) this;
        }

        public Criteria andHttpTypeNotBetween(String value1, String value2) {
            addCriterion("http_type not between", value1, value2, "httpType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNull() {
            addCriterion("request_type is null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNotNull() {
            addCriterion("request_type is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeEqualTo(String value) {
            addCriterion("request_type =", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotEqualTo(String value) {
            addCriterion("request_type <>", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThan(String value) {
            addCriterion("request_type >", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThanOrEqualTo(String value) {
            addCriterion("request_type >=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThan(String value) {
            addCriterion("request_type <", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThanOrEqualTo(String value) {
            addCriterion("request_type <=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLike(String value) {
            addCriterion("request_type like", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotLike(String value) {
            addCriterion("request_type not like", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIn(List<String> values) {
            addCriterion("request_type in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotIn(List<String> values) {
            addCriterion("request_type not in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeBetween(String value1, String value2) {
            addCriterion("request_type between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotBetween(String value1, String value2) {
            addCriterion("request_type not between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andApiaddressIsNull() {
            addCriterion("apiAddress is null");
            return (Criteria) this;
        }

        public Criteria andApiaddressIsNotNull() {
            addCriterion("apiAddress is not null");
            return (Criteria) this;
        }

        public Criteria andApiaddressEqualTo(String value) {
            addCriterion("apiAddress =", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressNotEqualTo(String value) {
            addCriterion("apiAddress <>", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressGreaterThan(String value) {
            addCriterion("apiAddress >", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressGreaterThanOrEqualTo(String value) {
            addCriterion("apiAddress >=", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressLessThan(String value) {
            addCriterion("apiAddress <", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressLessThanOrEqualTo(String value) {
            addCriterion("apiAddress <=", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressLike(String value) {
            addCriterion("apiAddress like", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressNotLike(String value) {
            addCriterion("apiAddress not like", value, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressIn(List<String> values) {
            addCriterion("apiAddress in", values, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressNotIn(List<String> values) {
            addCriterion("apiAddress not in", values, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressBetween(String value1, String value2) {
            addCriterion("apiAddress between", value1, value2, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andApiaddressNotBetween(String value1, String value2) {
            addCriterion("apiAddress not between", value1, value2, "apiaddress");
            return (Criteria) this;
        }

        public Criteria andRequestHeadIsNull() {
            addCriterion("request_head is null");
            return (Criteria) this;
        }

        public Criteria andRequestHeadIsNotNull() {
            addCriterion("request_head is not null");
            return (Criteria) this;
        }

        public Criteria andRequestHeadEqualTo(String value) {
            addCriterion("request_head =", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadNotEqualTo(String value) {
            addCriterion("request_head <>", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadGreaterThan(String value) {
            addCriterion("request_head >", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadGreaterThanOrEqualTo(String value) {
            addCriterion("request_head >=", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadLessThan(String value) {
            addCriterion("request_head <", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadLessThanOrEqualTo(String value) {
            addCriterion("request_head <=", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadLike(String value) {
            addCriterion("request_head like", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadNotLike(String value) {
            addCriterion("request_head not like", value, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadIn(List<String> values) {
            addCriterion("request_head in", values, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadNotIn(List<String> values) {
            addCriterion("request_head not in", values, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadBetween(String value1, String value2) {
            addCriterion("request_head between", value1, value2, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestHeadNotBetween(String value1, String value2) {
            addCriterion("request_head not between", value1, value2, "requestHead");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeIsNull() {
            addCriterion("requestParameterType is null");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeIsNotNull() {
            addCriterion("requestParameterType is not null");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeEqualTo(String value) {
            addCriterion("requestParameterType =", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotEqualTo(String value) {
            addCriterion("requestParameterType <>", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeGreaterThan(String value) {
            addCriterion("requestParameterType >", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeGreaterThanOrEqualTo(String value) {
            addCriterion("requestParameterType >=", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeLessThan(String value) {
            addCriterion("requestParameterType <", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeLessThanOrEqualTo(String value) {
            addCriterion("requestParameterType <=", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeLike(String value) {
            addCriterion("requestParameterType like", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotLike(String value) {
            addCriterion("requestParameterType not like", value, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeIn(List<String> values) {
            addCriterion("requestParameterType in", values, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotIn(List<String> values) {
            addCriterion("requestParameterType not in", values, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeBetween(String value1, String value2) {
            addCriterion("requestParameterType between", value1, value2, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparametertypeNotBetween(String value1, String value2) {
            addCriterion("requestParameterType not between", value1, value2, "requestparametertype");
            return (Criteria) this;
        }

        public Criteria andRequestparameterIsNull() {
            addCriterion("requestParameter is null");
            return (Criteria) this;
        }

        public Criteria andRequestparameterIsNotNull() {
            addCriterion("requestParameter is not null");
            return (Criteria) this;
        }

        public Criteria andRequestparameterEqualTo(String value) {
            addCriterion("requestParameter =", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterNotEqualTo(String value) {
            addCriterion("requestParameter <>", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterGreaterThan(String value) {
            addCriterion("requestParameter >", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterGreaterThanOrEqualTo(String value) {
            addCriterion("requestParameter >=", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterLessThan(String value) {
            addCriterion("requestParameter <", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterLessThanOrEqualTo(String value) {
            addCriterion("requestParameter <=", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterLike(String value) {
            addCriterion("requestParameter like", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterNotLike(String value) {
            addCriterion("requestParameter not like", value, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterIn(List<String> values) {
            addCriterion("requestParameter in", values, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterNotIn(List<String> values) {
            addCriterion("requestParameter not in", values, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterBetween(String value1, String value2) {
            addCriterion("requestParameter between", value1, value2, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andRequestparameterNotBetween(String value1, String value2) {
            addCriterion("requestParameter not between", value1, value2, "requestparameter");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andMockstatusIsNull() {
            addCriterion("mockStatus is null");
            return (Criteria) this;
        }

        public Criteria andMockstatusIsNotNull() {
            addCriterion("mockStatus is not null");
            return (Criteria) this;
        }

        public Criteria andMockstatusEqualTo(Byte value) {
            addCriterion("mockStatus =", value, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusNotEqualTo(Byte value) {
            addCriterion("mockStatus <>", value, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusGreaterThan(Byte value) {
            addCriterion("mockStatus >", value, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("mockStatus >=", value, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusLessThan(Byte value) {
            addCriterion("mockStatus <", value, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusLessThanOrEqualTo(Byte value) {
            addCriterion("mockStatus <=", value, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusIn(List<Byte> values) {
            addCriterion("mockStatus in", values, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusNotIn(List<Byte> values) {
            addCriterion("mockStatus not in", values, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusBetween(Byte value1, Byte value2) {
            addCriterion("mockStatus between", value1, value2, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockstatusNotBetween(Byte value1, Byte value2) {
            addCriterion("mockStatus not between", value1, value2, "mockstatus");
            return (Criteria) this;
        }

        public Criteria andMockCodeIsNull() {
            addCriterion("mock_code is null");
            return (Criteria) this;
        }

        public Criteria andMockCodeIsNotNull() {
            addCriterion("mock_code is not null");
            return (Criteria) this;
        }

        public Criteria andMockCodeEqualTo(String value) {
            addCriterion("mock_code =", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeNotEqualTo(String value) {
            addCriterion("mock_code <>", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeGreaterThan(String value) {
            addCriterion("mock_code >", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mock_code >=", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeLessThan(String value) {
            addCriterion("mock_code <", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeLessThanOrEqualTo(String value) {
            addCriterion("mock_code <=", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeLike(String value) {
            addCriterion("mock_code like", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeNotLike(String value) {
            addCriterion("mock_code not like", value, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeIn(List<String> values) {
            addCriterion("mock_code in", values, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeNotIn(List<String> values) {
            addCriterion("mock_code not in", values, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeBetween(String value1, String value2) {
            addCriterion("mock_code between", value1, value2, "mockCode");
            return (Criteria) this;
        }

        public Criteria andMockCodeNotBetween(String value1, String value2) {
            addCriterion("mock_code not between", value1, value2, "mockCode");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUserupdateIsNull() {
            addCriterion("userUpdate is null");
            return (Criteria) this;
        }

        public Criteria andUserupdateIsNotNull() {
            addCriterion("userUpdate is not null");
            return (Criteria) this;
        }

        public Criteria andUserupdateEqualTo(String value) {
            addCriterion("userUpdate =", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateNotEqualTo(String value) {
            addCriterion("userUpdate <>", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateGreaterThan(String value) {
            addCriterion("userUpdate >", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateGreaterThanOrEqualTo(String value) {
            addCriterion("userUpdate >=", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateLessThan(String value) {
            addCriterion("userUpdate <", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateLessThanOrEqualTo(String value) {
            addCriterion("userUpdate <=", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateLike(String value) {
            addCriterion("userUpdate like", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateNotLike(String value) {
            addCriterion("userUpdate not like", value, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateIn(List<String> values) {
            addCriterion("userUpdate in", values, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateNotIn(List<String> values) {
            addCriterion("userUpdate not in", values, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateBetween(String value1, String value2) {
            addCriterion("userUpdate between", value1, value2, "userupdate");
            return (Criteria) this;
        }

        public Criteria andUserupdateNotBetween(String value1, String value2) {
            addCriterion("userUpdate not between", value1, value2, "userupdate");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidIsNull() {
            addCriterion("ApiGroupLevelFirstId is null");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidIsNotNull() {
            addCriterion("ApiGroupLevelFirstId is not null");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidEqualTo(Integer value) {
            addCriterion("ApiGroupLevelFirstId =", value, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidNotEqualTo(Integer value) {
            addCriterion("ApiGroupLevelFirstId <>", value, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidGreaterThan(Integer value) {
            addCriterion("ApiGroupLevelFirstId >", value, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ApiGroupLevelFirstId >=", value, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidLessThan(Integer value) {
            addCriterion("ApiGroupLevelFirstId <", value, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidLessThanOrEqualTo(Integer value) {
            addCriterion("ApiGroupLevelFirstId <=", value, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidIn(List<Integer> values) {
            addCriterion("ApiGroupLevelFirstId in", values, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidNotIn(List<Integer> values) {
            addCriterion("ApiGroupLevelFirstId not in", values, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidBetween(Integer value1, Integer value2) {
            addCriterion("ApiGroupLevelFirstId between", value1, value2, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelfirstidNotBetween(Integer value1, Integer value2) {
            addCriterion("ApiGroupLevelFirstId not between", value1, value2, "apigrouplevelfirstid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidIsNull() {
            addCriterion("ApiGroupLevelSecondId is null");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidIsNotNull() {
            addCriterion("ApiGroupLevelSecondId is not null");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidEqualTo(Integer value) {
            addCriterion("ApiGroupLevelSecondId =", value, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidNotEqualTo(Integer value) {
            addCriterion("ApiGroupLevelSecondId <>", value, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidGreaterThan(Integer value) {
            addCriterion("ApiGroupLevelSecondId >", value, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ApiGroupLevelSecondId >=", value, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidLessThan(Integer value) {
            addCriterion("ApiGroupLevelSecondId <", value, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidLessThanOrEqualTo(Integer value) {
            addCriterion("ApiGroupLevelSecondId <=", value, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidIn(List<Integer> values) {
            addCriterion("ApiGroupLevelSecondId in", values, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidNotIn(List<Integer> values) {
            addCriterion("ApiGroupLevelSecondId not in", values, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidBetween(Integer value1, Integer value2) {
            addCriterion("ApiGroupLevelSecondId between", value1, value2, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andApigrouplevelsecondidNotBetween(Integer value1, Integer value2) {
            addCriterion("ApiGroupLevelSecondId not between", value1, value2, "apigrouplevelsecondid");
            return (Criteria) this;
        }

        public Criteria andProjectidIsNull() {
            addCriterion("projectId is null");
            return (Criteria) this;
        }

        public Criteria andProjectidIsNotNull() {
            addCriterion("projectId is not null");
            return (Criteria) this;
        }

        public Criteria andProjectidEqualTo(Integer value) {
            addCriterion("projectId =", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotEqualTo(Integer value) {
            addCriterion("projectId <>", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThan(Integer value) {
            addCriterion("projectId >", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThanOrEqualTo(Integer value) {
            addCriterion("projectId >=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThan(Integer value) {
            addCriterion("projectId <", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThanOrEqualTo(Integer value) {
            addCriterion("projectId <=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidIn(List<Integer> values) {
            addCriterion("projectId in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotIn(List<Integer> values) {
            addCriterion("projectId not in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidBetween(Integer value1, Integer value2) {
            addCriterion("projectId between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotBetween(Integer value1, Integer value2) {
            addCriterion("projectId not between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andResponseIsNull() {
            addCriterion("response is null");
            return (Criteria) this;
        }

        public Criteria andResponseIsNotNull() {
            addCriterion("response is not null");
            return (Criteria) this;
        }

        public Criteria andResponseEqualTo(String value) {
            addCriterion("response =", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseNotEqualTo(String value) {
            addCriterion("response <>", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseGreaterThan(String value) {
            addCriterion("response >", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseGreaterThanOrEqualTo(String value) {
            addCriterion("response >=", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseLessThan(String value) {
            addCriterion("response <", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseLessThanOrEqualTo(String value) {
            addCriterion("response <=", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseLike(String value) {
            addCriterion("response like", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseNotLike(String value) {
            addCriterion("response not like", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseIn(List<String> values) {
            addCriterion("response in", values, "response");
            return (Criteria) this;
        }

        public Criteria andResponseNotIn(List<String> values) {
            addCriterion("response not in", values, "response");
            return (Criteria) this;
        }

        public Criteria andResponseBetween(String value1, String value2) {
            addCriterion("response between", value1, value2, "response");
            return (Criteria) this;
        }

        public Criteria andResponseNotBetween(String value1, String value2) {
            addCriterion("response not between", value1, value2, "response");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_api
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_api
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}