package com.auth.dao;

import com.auth.entity.ApiReqHistory;
import com.auth.entity.ApiReqHistoryExample;
import java.util.List;

public interface ApiReqHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    int insert(ApiReqHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    int insertSelective(ApiReqHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    List<ApiReqHistory> selectByExample(ApiReqHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    ApiReqHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiReqHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_apiReqHistory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiReqHistory record);
}