package com.auth.dao;

import com.auth.entity.TestGlobalHost;
import com.auth.entity.TestGlobalHostExample;
import java.util.List;

public interface TestGlobalHostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_globalHost
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_globalHost
     *
     * @mbg.generated
     */
    int insert(TestGlobalHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_globalHost
     *
     * @mbg.generated
     */
    int insertSelective(TestGlobalHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_globalHost
     *
     * @mbg.generated
     */
    List<TestGlobalHost> selectByExample(TestGlobalHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_globalHost
     *
     * @mbg.generated
     */
    TestGlobalHost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_globalHost
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestGlobalHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_globalHost
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestGlobalHost record);
}