package com.auth.dao;

import com.auth.entity.CaseGroupFirst;
import com.auth.entity.CaseGroupFirstExample;
import java.util.List;

public interface CaseGroupFirstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseGroupFirst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseGroupFirst
     *
     * @mbg.generated
     */
    int insert(CaseGroupFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseGroupFirst
     *
     * @mbg.generated
     */
    int insertSelective(CaseGroupFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseGroupFirst
     *
     * @mbg.generated
     */
    List<CaseGroupFirst> selectByExample(CaseGroupFirstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseGroupFirst
     *
     * @mbg.generated
     */
    CaseGroupFirst selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseGroupFirst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaseGroupFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_caseGroupFirst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaseGroupFirst record);
}