package com.auth.dao;

import com.auth.entity.TestCase;
import com.auth.entity.TestCaseExample;
import java.util.List;

public interface TestCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_autocase
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_autocase
     *
     * @mbg.generated
     */
    int insert(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_autocase
     *
     * @mbg.generated
     */
    int insertSelective(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_autocase
     *
     * @mbg.generated
     */
    List<TestCase> selectByExample(TestCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_autocase
     *
     * @mbg.generated
     */
    TestCase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_autocase
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_autocase
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestCase record);
}