package com.auth.dao;

import com.auth.entity.TestProject;
import com.auth.entity.TestProjectExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

public interface TestProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_project
     *
     * @mbg.generated
     */
    int insert(TestProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_project
     *
     * @mbg.generated
     */
    int insertSelective(TestProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_project
     *
     * @mbg.generated
     */
    List<TestProject> selectByExample(TestProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_project
     *
     * @mbg.generated
     */
    TestProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestProject record);
}