package com.auth.dao;

import com.auth.entity.TestApi;
import com.auth.entity.TestApiExample;
import java.util.List;

public interface TestApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    int insert(TestApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    int insertSelective(TestApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    List<TestApi> selectByExampleWithBLOBs(TestApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    List<TestApi> selectByExample(TestApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    TestApi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TestApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestApi record);
}